### ISSUE TITLE
Basic Syntax and Structure

### ISSUE THREAD

**Issue by AshkanAfsharpour** [Dotnetflare/dotnetflare#8]
### Implement and document the fundamental syntax of C#, including program structure, variables, and basic operators.

**Tasks:**
- Create examples covering program structure, including namespaces, classes, and methods.
- Add documentation on variable declarations, data types, and comments.
- Implement examples of operators (arithmetic, relational, logical).

**Comment by mahdisalahi** [comment]
I can handle it...

**Comment by AshkanAfsharpour** [comment]
Thanks so much for taking on the fundamentals! For structure, let’s organize examples in separate folders to keep each core feature accessible. Feel free to start with simple console applications, each focusing on one topic like namespaces, classes, operators, etc. This should make it easier for contributors to add new examples and for users to find what they need quickly. Let me know if you need more details or have ideas for refining this approach!

**Comment by mahdisalahi** [comment]
> Thanks so much for taking on the fundamentals! For structure, let’s organize examples in separate folders to keep each core feature accessible. Feel free to start with simple console applications, each focusing on one topic like namespaces, classes, operators, etc. This should make it easier for contributors to add new examples and for users to find what they need quickly. Let me know if you need more details or have ideas for refining this approach!

I will try to organize the features that I plan to add in the best possible way.

**Comment by mahdisalahi** [comment]
Hi ashkan. I have a question for you. Is it necessary to add Bitwise Operators?
